services:
  web:
    image: nginx
    ports:
      - 85:80
    volumes:
      - './nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
      - './php:/var/www/html'

  php-fpm:
    build: ./docker
    volumes:
      - /home/galya/projects/my-env:/var/www/html

  db:
    image: postgres:13
    ports:
      - 54322:5432
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

